
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-application
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: dev

  # Source of the application manifests
  source:
    repoURL: github.com
    targetRevision: HEAD
    path: overlays/dev
   
    # directory
    directory:
      recurse: false
  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  # Sync policy
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: false # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
  



# apiVersion: argoproj.io/v1alpha1
# kind: ApplicationSet
# metadata:
#   name: dev-applicationset
# spec:
#   generators:
#     - git:
#         repoURL: 'https://your-git-repo-url.git'
#         revision: main
#         directories:
#           - path: 'overlays/dev'   # Path to the dev overlay in your repo
#   template:
#     metadata:
#       name: dev-application
#     spec:
#       project: default
#       source:
#         repoURL: 'https://your-git-repo-url.git'
#         targetRevision: main
#         path: overlays/dev
#       destination:
#         server: 'https://dev-cluster-url'  # URL of the dev cluster
#         namespace: dev-namespace
#       syncPolicy:
#         automated:
#           prune: true
#           selfHeal: true

